# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TQvzkDW0_X9IR29yAIk7lTR7H-K4SWt4
"""

import pandas as pd
f = pd.read_csv('sample_data/california_housing_test.csv')

f.shape

f.dtypes

f.isnull()

f.isnull().sum()

print(f['median_house_value'].mean())

f['median_income']

import pandas as pd
f = pd.read_csv('sample_data/california_housing_test.csv')

f[f['median_income'] < 2]

f[['longitude', 'latitude']]

"""задача 59 (4)"""

f[(f['housing_median_age'] < 20) & (f['median_house_value'] > 70000)]

"""задача 61 (1) Определить какое максимальное и минимальное значение median_house_value

"""

f['median_house_value'].max()

f['median_house_value'].min()

"""задача 61 (2) Показать максимальное median_house_value, где median_income = 3.1250"""

import pandas as pd
f = pd.read_csv('sample_data/california_housing_test.csv')

f[f['median_income'] == 3.1250]['median_house_value'].max()

"""задача 61 (3) Узнать какая максимальная population в зоне минимального значения median_house_value"""

f[f['median_house_value'] == f['median_house_value'].min()]['population'].max()

"""Домашнее задание к семинару 9. Задача 40. Работать с файлом california_housing_train.csv, который находится в папке sample_data. Определить среднюю стоимость дома, где кол-во людей от 0 до 500 (population)"""

import pandas as pd
f = pd.read_csv('sample_data/california_housing_train.csv')

f[f['population'] <= 500]['median_house_value'].median()

"""Задача 42. Узнать какая максимальная households в зоне минимального значения population"""

import pandas as pd
f = pd.read_csv('sample_data/california_housing_train.csv')

f['population'].min()

f[f['population'] == f['population'].min()]['households'].max()